In [1]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

# Array operations (vectorization)
print(arr1 * 2)  # Multiply each element by 2
print(arr1 + arr1)  # Add arrays element-wise

# Reshaping
arr3 = np.arange(12).reshape(3, 4)  # Create 3x4 array from 0-11
print(arr3)

# Matrix operations
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(np.dot(matrix1, matrix2))  # Matrix multiplication

# Statistical operations
data = np.random.normal(0, 1, 1000)  # 1000 random numbers from normal distribution
print(f"Mean: {data.mean()}, Std: {data.std()}")

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[19 22]
 [43 50]]
Mean: -0.007148255841317831, Std: 1.0239821710196828
